name: Viraindo Scraper

on:
  schedule:
    - cron: '0 2 * * 1'  # Runs at 2 AM every Monday (or any preferred time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests fake-useragent pandas-gbq google-auth lxml

    - name: Run Viraindo scraper
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: python scraping/viraindo.py
